version: "3.4"
volumes:
  shared-volume:
services:
  shared-tmp:
    image: busybox
    command: chmod -R 777 /tmp/docker
    volumes:
      - shared-volume:/tmp/docker
  mysql:
    image: mysql:${MYSQL_DOCKER_VERSION}
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: "db_imi_test"
      TZ: "Asia/Shanghai"
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s

  swoole:
    container_name: "swoole"
    depends_on:
      - shared-tmp
      - mysql
    environment:
      MYSQL_SERVER_HOST: mysql
      MYSQL_SERVER_PASSWORD: ""
    build:
      context: .
      dockerfile: swoole.dockerfile
      args:
        SWOOLE_DOCKER_VERSION: ${SWOOLE_DOCKER_VERSION}
    volumes:
      - "${GITHUB_WORKSPACE}:/imi:rw"
      - "/tmp/composer:/root/.composer/cache/files:rw"
      - shared-volume:/tmp/docker
    working_dir: /imi
    command: tail -f /dev/null

  swoole-only:
    container_name: "swoole-only"
    build:
      context: .
      dockerfile: swoole.dockerfile
      args:
        SWOOLE_DOCKER_VERSION: ${SWOOLE_DOCKER_VERSION}
    volumes:
      - "${GITHUB_WORKSPACE}:/imi:rw"
      - "/tmp/composer:/root/.composer/cache/files:rw"
      - "/tmp/phpstan:/tmp/phpstan:rw"
    working_dir: /imi
    command: tail -f /dev/null