name: 'ci-prepare'
description: 'ci-prepare'

inputs:
  env:
    required: true
    description: 'Env Service Name'

runs:
  using: composite
  steps:
    - name: Setup Services
      shell: bash
      run: |
        docker-compose -f ./.github/docker-compose.yml up -d ${{ inputs.env }}
        docker ps
        docker exec ${{ inputs.env }} php -v
        docker exec ${{ inputs.env }} php -m
        docker exec ${{ inputs.env }} php --ri swoole
        docker exec ${{ inputs.env }} php -r "echo 'opcache config: '; print_r(opcache_get_status(false));"
        docker exec ${{ inputs.env }} composer -V
    - name: Prepare
      shell: bash
      run: |
        docker exec ${{ inputs.env }} composer config -g process-timeout 600
        docker exec ${{ inputs.env }} composer update --no-interaction --prefer-dist --no-progress
