name: ci

on: [push, pull_request]

jobs:
  ci-php:
    name: Linux Swoole-${{ matrix.swoole.version }}
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        swoole: 
          - version: 4.8-php7.4
          - version: 4.8-php8.0
          - version: 4.7-php7.4
          - version: 4.7-php8.0
    env:
      ENV_SERVICE: swoole
      SWOOLE_DOCKER_VERSION: ${{ matrix.swoole.version }}
      MYSQL_DOCKER_VERSION: '8.0'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: /tmp/composer
          key: ${{ runner.os }}-composer-${{ matrix.swoole.version }}-${{ hashFiles('**/composer.json') }}
      - name: Prepare
        uses: ./.github/actions/ci-prepare
        with:
          env: ${{ env.ENV_SERVICE }}
      - name: Test
        run: docker exec ${ENV_SERVICE} composer test
      - name: Print logs
        if: failure()
        run: docker exec ${ENV_SERVICE} php .github/print-logs.php
