name: Static Code Analysis

on: [push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-20.04
    env:
      SWOOLE_DOCKER_VERSION: 4.8-php7.4
      ENV_SERVICE: swoole-only
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Prepare
        run: |
          docker-compose -f ./.github/docker-compose.yml up -d ${ENV_SERVICE}
          docker exec ${ENV_SERVICE} php -v
          docker exec ${ENV_SERVICE} php -m
          docker exec ${ENV_SERVICE} php --ri swoole
          docker exec ${ENV_SERVICE} composer -V
          docker exec ${ENV_SERVICE} composer update --no-interaction --prefer-dist --no-progress

      - name: Analyse
        run: |
          docker exec ${ENV_SERVICE} ./vendor/bin/phpstan analyse --memory-limit 1G